// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi0lZznIJXCBrAoAwC8EV4vDmcKqOXbOM',
    appId: '1:347020498011:web:dea1efd2a47936cf065b7e',
    messagingSenderId: '347020498011',
    projectId: 'fast-travel-cbd10',
    authDomain: 'fast-travel-cbd10.firebaseapp.com',
    storageBucket: 'fast-travel-cbd10.firebasestorage.app',
    measurementId: 'G-7FM3CGJ98G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy507HXKRvB-CCh2-wJk-9S8tJotBtyDs',
    appId: '1:347020498011:android:c6625eba7b451f05065b7e',
    messagingSenderId: '347020498011',
    projectId: 'fast-travel-cbd10',
    storageBucket: 'fast-travel-cbd10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB5uWuoz1eoMJazlMqzKqkcenfeGJxrYo',
    appId: '1:347020498011:ios:2b9db1a288622fa0065b7e',
    messagingSenderId: '347020498011',
    projectId: 'fast-travel-cbd10',
    storageBucket: 'fast-travel-cbd10.firebasestorage.app',
    iosClientId: '347020498011-1m0nusiqrecrstg9i4dlfskcn8lk894g.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastTravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB5uWuoz1eoMJazlMqzKqkcenfeGJxrYo',
    appId: '1:347020498011:ios:2b9db1a288622fa0065b7e',
    messagingSenderId: '347020498011',
    projectId: 'fast-travel-cbd10',
    storageBucket: 'fast-travel-cbd10.firebasestorage.app',
    iosClientId: '347020498011-1m0nusiqrecrstg9i4dlfskcn8lk894g.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastTravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi0lZznIJXCBrAoAwC8EV4vDmcKqOXbOM',
    appId: '1:347020498011:web:478335eeb2162549065b7e',
    messagingSenderId: '347020498011',
    projectId: 'fast-travel-cbd10',
    authDomain: 'fast-travel-cbd10.firebaseapp.com',
    storageBucket: 'fast-travel-cbd10.firebasestorage.app',
    measurementId: 'G-40RCK7LV0C',
  );
}
